### ISSUE TITLE
Peer to peer code review by Team-65-the-labradors

### ISSUE THREAD

**Issue by euqueme** [AlfredoElizarraras/blog-app#1]
Hello Oscar, Good job so far

Your Rubocop is only displaying a few errors we don't think it has anything to do with the configure files and after running rubocop - a only 7 errors remained that you should check out for instance these errors: 

```ruby
spec/requests/authors_spec.rb:78:63: E: Lint/Syntax: unexpected token tIDENTIFIER
(Using Ruby 2.7 parser; configure using TargetRubyVersion parameter, under AllCops)
      it 'renders a successful response (i.e. to display the 'new' template)' do
                                                              ^^^
spec/requests/authors_spec.rb:107:63: E: Lint/Syntax: unexpected token tIDENTIFIER
(Using Ruby 2.7 parser; configure using TargetRubyVersion parameter, under AllCops)
      it 'renders a successful response (i.e. to display the 'edit' template)' do
```
could be fixed by using double quotes for the 'new' and 'edit' words so it looks like this for example:

```ruby
.
.
      it 'renders a successful response (i.e. to display the "new" template)' do
        post authors_url, params: { author: invalid_attributes }
        expect(response).to be_successful
      end
.
.
```

There are still some more errors but you can be free to ask us any time

Keep up the good work!

Happy Coding! :rocket:

**Comment by AlfredoElizarraras** [comment]
Hi there Maria, thanks for the feedback. 
Carlos and I fix the offenses so I am closing the issue.
Happy coding too! ^.^
